### ISSUE TITLE
Rework 1.7 Heartbeat

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#1444]
> As of 2020-02-03, the main issue has been fixed by implementing the original (MS1.5) up-counting heartbeat.
> For the final MS1.7 implementation, I still would suggest to check the proposed method using the official midi system command "Active Sensing" as described [here:]

> Any MIDI data is acceptable, but actually there IS a command already reserved for this kind of signalling that we could re-use, even though it was originally intended to be send to the receiver :
> "Active Sensing" (0xFE), which shall be sent every 300ms max (we would adapt that to 100ms max).
> See https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message, scroll down to end of page.

**Comment by MatthiasSeeber** [comment]
If I understand this correctly, the "Active Sensing" strategy is to transmit a single Status byte (0xFE) in order to indicate that the connection is still active. In other words, no real value is transmitted. This seems to undermine the current strategy of counting heartbeats throughout the system..?

**Comment by KlausStrohhaecker** [comment]
1) Up-counting heartbeats may or may not still be used in MS1.7 but the PG can now communicate directly with the AE, no need to pipe AE heartbeats through the LPC to the Playground.
Therefore, sending the "Active Sensing" down to the LPC is  sufficient.
After Reset, the LPC senses this command (actually, an incoming traffic on USB-MIDI) and will not send any data over MIDI to the AE until this happens, to avoid buffer overruns etc.
In turn, the LPC should echo the "Active Sensing" so AE knows if LPC is alive and may do "emergency note off" if the LPC fails to respond. <== I would suggest to implement this.

2) Further, the LPC will still send its own unconditionally up-counting heartbeat up to the Bridge which is used by the PG to detect basic LPC state (in order to resend all the required parameters and config data the LPC needs to run). Looks like the current MS1.7 PG (NAMM Preview) does NOT react on the LPC heartbeat anymore ;-(

**Comment by MatthiasSeeber** [comment]
I wouldn't mind the Audio Engine switching to the Active Sensing method in order to signal its presence to the LPC, as it would reduce code complexity and a tiny little CPU consumption on AE-side for this task.

But I fail to see advantages of the other direction (LPC sends Active Sensing to AE), as this would re-complicate things on AE-side. Especially when there already is a place for detection and handling of the LPC-status present (may that BBBB or PG, and disregarding potential current functionality loss). Via WebSocket, PG or BBBB could send a ResetAudioEngine message in order to ensure silence - and the AudioEngine remains a mindless renderer. Right?

**Comment by KlausStrohhaecker** [comment]
It was just meant as a possible additional safeguard for the pitfalls of event-based systems with carrier-less unprotected data channels (channels not knowing if they are actually connected or not at any time, at the higher protocol levels).
Since the details of how we are going to do all the total system state syncing are not fully worked out yet, I think it's a good idea to implement the simple low-level stuff.
In this case it would mean I'll try implement the echoing, check if it upsets the AE and then we can still decide later whether there's any benefit using it. Traffic and processing penalty is minimal, it seems.

**Comment by MatthiasSeeber** [comment]
Alright, here is a diagram from the 1.7 planning phase, showing the main components and their interactions:
![image4](https://user-images.githubusercontent.com/37212609/74165835-f8ce6c00-4c25-11ea-90b7-184b41ad0e0a.png)
We may want to re-evaluate this, adding the Supervisor and additional messages and safeguard mechanisms.

**Comment by KlausStrohhaecker** [comment]
Push....

**Comment by hhoegelo** [comment]
This was fixed with commit 8a0b3032ef268903fc80f3d8d44f978f5fab47e8.

**Comment by KlausStrohhaecker** [comment]
For some reason it still doesn't work. I can confirm that PG scans LPC heartbeats and detect if they start to miss and then come back again, issueing warning messages like `Apr 30 18:23:33 apl playground[1358]: Warning:  LPCProxy had to re-send the edit buffer, as the heartbeat stumbled from>` and may have reinitinitialized the Audio Engine, but did NOT send the LPC global setup (velocity settings etc.).

To be exactly correct, the PG should sent the global LPC setup data only once after it goes online (or online, again), as it has nothing to do with the edit buffer and preset management at all.
In MS1.5 and before, PG used to send the global data with every preset change/load or other edit buffer transmit which is not really adequate but was established this way for probably historic reasons of conveninence (and maybe we should keep it like this, this kind of redundancy isn't a problem, and the LPC code has been adapted do deal with that redundancy).

**Comment by KlausStrohhaecker** [comment]
I checked more details:
- when the LPC zeros the heartbeat counter while running normally (implemented with a special BB message), the tested setting**) was NOT re-sent, although the PG issues its "LPCProxy had to re-send the edit buffer" warning.
- when the LPC is actually reset while playground is running, the tested setting**) also was NOT re-sent, although the PG issues its "LPCProxy had to re-send the edit buffer" warning.
- when the LPC is actually reset while playground is NOT running, the tested setting**) was sent twice(!) (and AE re-initialized) when playground starts, this is also the power-up scenario. Again with the "re-send" warning, this time the counter being lower than max(uint64_t), the forcing initial condition.

I checked that the heartbeats are actually enabled in the LPC, after reset, at a time when it is ready to receive commands from the lpc_bb_driver, even introduced a (temporary) 2.5 seconds delay before heartbeats start, but it didn't help, LPC code seemingly not being part of the problem.

**) I used the "set velocity curve" message for debugging, turning some LEDs for some time on when it is received, because that was the symptom I found in the previous post (velocity curve no set after LPC reset).

In a second test I lit the LEDs on ANY "setting"-type message received and it turned out that seemingly some settings DO get transmitted, as the LEDs went on in the two fault scenarios from the above list. Also, it was found that in scenario 3 (PG restart) settings are transferred three times, mabye the same ones, maybe different ones (did't check).

==> Conclusion: looks like sometimes not all required settings are transmitted. For some reason the PG seems to make a difference between "initial" settings (transmitted after it starts) and "resend" settings (when lower LPC heartbeats numbers than before are picked up, which of course also happens right after it starts)?

It should be checked that ALL settings are actually send, as per following list of setting IDs currently in use (from https://github.com/nonlinear-labs-dev/C15/blob/LPC/projects/shared/lpc-defs.h):
```
  LPC_SETTING_ID_PLAY_MODE_UPPER_RIBBON_BEHAVIOUR = 0,       // ==> BIT 0 set if (returnMode == RETURN), ...
  LPC_SETTING_ID_PLAY_MODE_LOWER_RIBBON_BEHAVIOUR = 1,       // ... BIT 1 set if (touchBehaviour == RELATIVE)
  LPC_SETTING_ID_BASE_UNIT_UI_MODE                = 3,       // ==> PLAY = 0, PARAMETER_EDIT = 1
  LPC_SETTING_ID_EDIT_MODE_RIBBON_BEHAVIOUR       = 4,       // ==> RELATIVE = 0, ABSOLUTE = 1
  LPC_SETTING_ID_UPPER_RIBBON_REL_FACTOR          = 9,       // ==> tTcdRange(256, 2560)
  LPC_SETTING_ID_LOWER_RIBBON_REL_FACTOR          = 10,      // ==> tTcdRange(256, 2560)
  LPC_SETTING_ID_VELOCITY_CURVE                   = 11,      // ==> VERY_SOFT = 0, SOFT = 1, NORMAL = 2, HARD = 3, VERY_HARD = 4
  LPC_SETTING_ID_PEDAL_1_TYPE                     = 26,      // ==> PotTipActive  = 0
  LPC_SETTING_ID_PEDAL_2_TYPE                     = 27,      // ... PotRingActive = 1
  LPC_SETTING_ID_PEDAL_3_TYPE                     = 28,      // ... SwitchClosing = 2 // aka momentary switch, normally open
  LPC_SETTING_ID_PEDAL_4_TYPE                     = 29,      // ... SwitchOpening = 3 // aka momentary switch, normally closed
  LPC_SETTING_ID_AFTERTOUCH_CURVE                 = 30,      // SOFT = 0, NORMAL = 1, HARD = 2
  LPC_SETTING_ID_BENDER_CURVE                     = 31,      // SOFT = 0, NORMAL = 1, HARD = 2
```

**Comment by KlausStrohhaecker** [comment]
Looks the underlying problem is something else, see #1891

**Comment by schlenkibus** [comment]
@KlausStrohhaecker dieses Ticket kann nach dem merge von KSTR-PedalUI geschlossen werden oder was sagst du?

**Comment by KlausStrohhaecker** [comment]
Ja, nachdem der LPC bug weg ist, und das Senden jetzt sauberer, ich schließe...
